### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Like #11 plus https://python-future.org/automatic_conversion.html?highlight=stage#stage-1-safe-fixes, etc.

### CODE REVIEW

**Comment by cclauss** [comment]
Tests failing.

**Comment by edsu** [comment]
Would merging this make it easier to work on?

**Comment by cclauss** [comment]
Yes please.

**Comment by edsu** [comment]
I have removed ez_setup.py - hopefully that's not a problem?

**Pull request merged**
